### ISSUE TITLE
[Errno 13] Permission denied: '/dev/ttyUSB0'

### ISSUE THREAD

**Issue by achimwessling** [merlinschumacher/Basecamp#32]
Ich versuche auf einem Linux-Rechner (Antergos; Arch-based; 64-Bit) einen ganz simplen Sketch per **Sketch** - **Hochladen** aus der Arduino-IDE an mein Board zu senden.

Leider erhalte ich folgenden Fehler:
```
Der Sketch verwendet 893146 Bytes (68%) des Programmspeicherplatzes. Das Maximum sind 1310720 Bytes.
Globale Variablen verwenden 46848 Bytes (15%) des dynamischen Speichers, 248064 Bytes für lokale Variablen verbleiben. Das Maximum sind 294912 Bytes.
esptool.py v2.1
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
PermissionError: [Errno 13] Permission denied: '/dev/ttyUSB0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/achim/Arduino/hardware/espressif/esp32/tools/esptool.py", line 2524, in <module>
    _main()
  File "/home/achim/Arduino/hardware/espressif/esp32/tools/esptool.py", line 2517, in _main
    main()
  File "/home/achim/Arduino/hardware/espressif/esp32/tools/esptool.py", line 2246, in main
    esp = chip_class(args.port, initial_baud)
  File "/home/achim/Arduino/hardware/espressif/esp32/tools/esptool.py", line 177, in __init__
    self._port = serial.serial_for_url(port)
  File "/usr/lib/python3.6/site-packages/serial/__init__.py", line 88, in serial_for_url
    instance.open()
  File "/usr/lib/python3.6/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
Der ausgewählte serielle Port serial.serialutil.SerialException: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
 ist nicht vorhanden oder das Board ist nicht angeschlossen
```

Arch verwendet Python 3. Könnte da ein Problem liegen?

Ich bin für jeden Hinweis dankbar!

**Comment by pici** [comment]
die Antwort auf Deine Frage steht hier:
Permission denied: '/dev/ttyUSB0'

die Lösung:
das script als root bzw. sudo auführen
oder besser
in /etc/group den Eintrag uucp suchen und dort deinen user-Namen eintragen.
Beispiel:
uucp:x:14:meinuser

**Comment by pici** [comment]
so sollte das Beispiel aussehen:
`uucp:x:14:pic`

**Comment by achimwessling** [comment]
JA! Dann darf ich schreiben, ...

ABER da taucht schon das nächste Problem auf! Für mich sieht es aus, als würde er nicht nicht sauber fertig werden, da ich kein WLAN Passwort erhalte.

Consolenausgabe endet so:
```

Writing at 0x00054000... (58 %)
Writing at 0x00058000... (61 %)
Writing at 0x0005c000... (64 %)
Writing at 0x00060000... (67 %)
Writing at 0x00064000... (70 %)
Writing at 0x00068000... (74 %)
Writing at 0x0006c000... (77 %)
Writing at 0x00070000... (80 %)
Writing at 0x00074000... (83 %)
Writing at 0x00078000... (87 %)
Writing at 0x0007c000... (90 %)
Writing at 0x00080000... (93 %)
Writing at 0x00084000... (96 %)
Writing at 0x00088000... (100 %)
Wrote 894288 bytes (505643 compressed) at 0x00010000 in 44.9 seconds (effective 159.5 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 122...

Writing at 0x00008000... (100 %)
Wrote 3072 bytes (122 compressed) at 0x00008000 in 0.0 seconds (effective 1565.1 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting...
```

Mein Code ist identisch zu dem aus Eurem Artikel:

```
#include <Basecamp.hpp>

Basecamp iot {
  Basecamp::
  SetupModeWifiEncryption::
  secured
};

void setup() {
  iot.begin();
}

void loop() {}
```

**Comment by merlinschumacher** [comment]
Die Ausgaben sind nicht die auf der Seriellen Konsole, sondern die Compilerausgaben. 
Die serielle Konsole finden Sie in der IDE unter Werkzeuge.

**Comment by achimwessling** [comment]
DANKE!
